# Generated by Django 4.1 on 2022-08-20 17:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0003_message1_remove_room_allowed_users_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Message1",
            new_name="Message",
        ),
    ]
